spring:
  datasource:
    write:
      url: jdbc:mysql://localhost:3306/데이터베이스?serverTimezone=UTC&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 12345
    read:
      url: jdbc:mysql://localhost:3306/데이터베이스?serverTimezone=UTC&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 12345
  data:
    mongodb:
      uri: mongodb://localhost:27017/mycar
      auto-index-creation: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.todaycar: DEBUG
server:
  port: 8080
